### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by JAMoreno-Larios** [WANGRUOGU/SL-PRU#3]
Hello Rougu,

Thank you for uploading your implementation of SL-PRU to GitHub. My Name is José Moreno and I am a postdoctoral researcher at Batista-Brito and Sjulson's laboratories in Albert Einstein College of Medicine. We are currently developing an hyperspectral microscopy application for transcriptomics and I think it may be worthwhile to incorporate your code into our workflow. However, I did not find any license file in your repo so I'm not sure how to proceed with your code.

Thank you,

José

**Comment by WANGRUOGU** [comment]
Hi José,

Thanks for your interest. I'm sorry I'm not familiar with licensing. But this code is related to my paper in this link "https://doi.org/10.1093/bioinformatics/btad159". Is it good for you?

Best,
Ruogu

**Comment by JAMoreno-Larios** [comment]
Hi Rougu,

I was talking about something along this site: https://choosealicense.com/no-permission/

A license can help define the scope of how people can interact with your code, and what they are allowed to do with it. There is more information on this page, too: https://choosealicense.com/

Thank you,
José

**Comment by WANGRUOGU** [comment]
Hi José,
Thanks for your message. I just added a liscense in the readme file. Please let me know if it is good for you. 

Best,
Ruogu

**Comment by JAMoreno-Larios** [comment]
This is great, thank you!

Best,

José

Aug 2, 2023 10:43:41 WANGRUOGU ***@***.***>:
